import type { ForecastGrid } from '../shared/types';

// Expand this list to every service area you support before enabling production schedules.
export const FORECAST_GRIDS: ForecastGrid[] = [
  {
    regionKey: 'seoul',
    stationName: '서울특별시 강남구 역삼동',
    stationNames: [
      '서울특별시 강남구 역삼동',
      '강남구',
      '역삼동',
      '서울특별시 종로구 사직동',
      '종로구',
      '서울특별시 송파구',
      '송파구',
      '서울특별시 성북구',
      '성북구',
      '서울특별시 서대문구',
      '서대문구',
      '서울특별시 중구',
      '서울 중구',
    ],
    sidoName: '서울',
    nx: 61,
    ny: 125,
  },
  {
    regionKey: 'busan',
    stationName: '부산광역시 해운대구 우동',
    stationNames: [
      '부산광역시 해운대구 우동',
      '해운대구',
      '우동',
      '좌동',
      '부산광역시 중구 영주동',
      '광복동',
      '부산광역시 서구',
      '대신동',
      '부산광역시 동구',
      '초량동',
      '부산광역시 영도구',
      '영도구',
      '태종대',
      '청학동',
      '부산광역시 부산진구',
      '부산진구',
      '전포동',
      '개금동',
      '부산광역시 동래구',
      '동래구',
      '명장동',
      '부산광역시 남구',
      '대연동',
      '용호동',
      '부산광역시 북구',
      '화명동',
      '덕천동',
      '부산광역시 사하구',
      '사하구',
      '당리동',
      '장림동',
      '부산광역시 금정구',
      '금정구',
      '청룡동',
      '부산광역시 강서구 대저1동',
      '명지동',
      '녹산동',
      '대저동',
      '부산광역시 연제구',
      '연제구',
      '연산동',
      '부산광역시 수영구',
      '수영구',
      '광안동',
      '부산광역시 사상구',
      '사상구',
      '학장동',
      '삼락동',
      '부산광역시 기장군',
      '기장군',
      '기장읍',
    ],
    sidoName: '부산',
    nx: 99,
    ny: 75,
  },
  {
    regionKey: 'daegu',
    stationName: '대구광역시 수성구 지산동',
    stationNames: [
      '대구광역시 수성구 지산동',
      '지산동',
      '만촌동',
      '대구광역시 수성구 범어동',
      '수성구',
    ],
    sidoName: '대구',
    nx: 90,
    ny: 90,
  },
  {
    regionKey: 'incheon',
    stationName: '인천광역시 연수구 송도동',
    stationNames: [
      '인천광역시 연수구 송도동',
      '송도',
      '동춘',
      '청라',
      '인천광역시 남동구 만수동',
      '구월동',
      '논현',
    ],
    sidoName: '인천',
    nx: 54,
    ny: 123,
  },
  {
    regionKey: 'gwangju',
    stationName: '광주광역시 북구 용봉동',
    stationNames: [
      '광주광역시 북구 용봉동',
      '운암동',
      '두암동',
      '일곡동',
      '건국동',
      '광주광역시 광산구 우산동',
      '평동',
      '치평동',
    ],
    sidoName: '광주',
    nx: 59,
    ny: 75,
  },
  {
    regionKey: 'daejeon',
    stationName: '대전광역시 유성구 봉명동',
    stationNames: [
      '대전광역시 유성구 봉명동',
      '구성동',
      '관평동',
      '노은동',
      '유성구',
    ],
    sidoName: '대전',
    nx: 67,
    ny: 100,
  },
  {
    regionKey: 'ulsan',
    stationName: '울산광역시 남구 삼산동',
    stationNames: [
      '울산광역시 남구 삼산동',
      '울산광역시 북구 염포동',
      '효문동',
      '농소동',
      '삼산동',
    ],
    sidoName: '울산',
    nx: 102,
    ny: 84,
  },
  {
    regionKey: 'sejong',
    stationName: '세종특별자치시 아름동',
    stationNames: [
      '세종특별자치시 아름동',
      '세종시',
      '세종특별자치시',
      '아름동',
      '보람동',
      '한솔동',
      '조치원읍',
    ],
    sidoName: '세종',
    nx: 65,
    ny: 104,
  },
  {
    regionKey: 'gyeonggi',
    stationName: '경기도 성남시 분당구 정자동',
    stationNames: [
      '경기도 성남시 분당구 정자동',
      '성남시 분당구',
      '분당구',
      '정자동',
      '수내동',
      '운중동',
      '경기도 고양시 일산동구 장항동',
      '주엽동',
      '행신동',
      '식사동',
    ],
    sidoName: '경기',
    nx: 62,
    ny: 122,
  },
  {
    regionKey: 'gangwon',
    stationName: '강원특별자치도 춘천시 석사동',
    stationNames: [
      '강원특별자치도 춘천시 석사동',
      '춘천시',
      '석사동',
      '강원특별자치도 원주시 단계동',
      '문막읍',
    ],
    sidoName: '강원',
    nx: 73,
    ny: 133,
  },
  {
    regionKey: 'chungbuk',
    stationName: '충청북도 청주시 흥덕구 복대동',
    stationNames: [
      '충청북도 청주시 흥덕구 복대동',
      '복대동',
      '충청북도 충주시 연수동',
      '호암동',
      '칠금동',
    ],
    sidoName: '충북',
    nx: 68,
    ny: 107,
  },
  {
    regionKey: 'chungnam',
    stationName: '충청남도 천안시 서북구 불당동',
    stationNames: [
      '충청남도 천안시 서북구 불당동',
      '천안시 서북구',
      '성황동',
      '백석동',
      '성성동',
      '신방동',
      '불당동',
    ],
    sidoName: '충남',
    nx: 62,
    ny: 110,
  },
  {
    regionKey: 'jeonbuk',
    stationName: '전북특별자치도 전주시 완산구 효자동',
    stationNames: [
      '전북특별자치도 전주시 완산구 효자동',
      '전주시 완산구',
      '효자동',
    ],
    sidoName: '전북',
    nx: 63,
    ny: 88,
  },
  {
    regionKey: 'jeonnam',
    stationName: '전라남도 여수시 학동',
    stationNames: [
      '전라남도 여수시 학동',
      '여수시',
      '삼일동',
      '문수동',
      '율촌면',
      '월내동',
      '여수항',
      '전라남도 목포시 상동',
      '부흥동',
      '용당동',
      '학동',
    ],
    sidoName: '전남',
    nx: 73,
    ny: 66,
  },
  {
    regionKey: 'gyeongbuk',
    stationName: '경상북도 포항시 남구 대잠동',
    stationNames: [
      '경상북도 포항시 남구 대잠동',
      '포항시 남구',
      '장흥동',
      '대도동',
      '연일읍',
      '장량동',
      '청림동',
      '대잠동',
    ],
    sidoName: '경북',
    nx: 102,
    ny: 94,
  },
  {
    regionKey: 'gyeongnam',
    stationName: '경상남도 창원시 성산구 중앙동',
    stationNames: [
      '경상남도 창원시 성산구 중앙동',
      '창원시 성산구',
      '성주동',
      '웅남동',
      '사파동',
      '명서동',
      '회원동',
      '경상남도 김해시 내동',
      '장유동',
      '삼방동',
      '동상동',
      '진영읍',
      '중앙동',
    ],
    sidoName: '경남',
    nx: 91,
    ny: 76,
  },
  {
    regionKey: 'jeju',
    stationName: '제주특별자치도 제주시 연동',
    stationNames: [
      '제주특별자치도 제주시 연동',
      '제주시',
      '연동',
    ],
    sidoName: '제주',
    nx: 52,
    ny: 37,
  },
];
